### ISSUE TITLE
Can it be used on Windows10?

### ISSUE THREAD

**Issue by scillidan** [micouy/kn#14]
A nice useful tool.
I used `Cmder` on Windows10.
Have `kn` considered working on them?

**Comment by micouy** [comment]
@scillidan I haven't worked with either `Cmder` or Windows shells and I'm not planning to implement it myself. However feel free to file a PR for it.

Extending `kn` support to other shells requires (1) adding a shell script analogous to those in [`init/`](https://github.com/micouy/kn/tree/master/init), (2) adding the desired shell to the [`init` command](https://github.com/micouy/kn/blob/master/src/init.rs) and (3) adding [configuration instructions](https://github.com/micouy/kn#configuring-your-shell). To fully support Windows, the [GitHub workflow](https://github.com/micouy/kn/blob/master/.github/workflows/build-binaries.yml) should be modified to generate Windows binaries.

**Comment by scillidan** [comment]
Thanks for your reply and hint :)
This is a new thing and challenge for me.
I would like to give it a try.
