### ISSUE TITLE
G_LIBC_2.18 not found

### ISSUE THREAD

**Issue by elkarouh** [micouy/kn#7]
I am on old linux machine and the linux executable requires a specific version of g_libc.
Can you provide a musl version (the same way ripgrep does)?
Many thanks

**Comment by micouy** [comment]
Could you check if it works?

[kn-x86_64-unknown-linux-musl.zip](https://github.com/micouy/kn/files/6317376/kn-x86_64-unknown-linux-musl.zip)

**Comment by elkarouh** [comment]
It seems to work !
Thanks

**Comment by micouy** [comment]
cool
